import { AppStateProvider } from './context/AppStateContext';
import { Toaster } from 'react-hot-toast';
import Header from './components/header/Header';
import UploadBar from './components/upload_bar/UploadBar';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<AppStateProvider>
					<Header />
					<UploadBar />
					<Toaster
						position='top-center'
						reverseOrder={false}
						toastOptions={{
							duration: 5000
						}}
					/>
				</AppStateProvider>
				{children}
			</body>
		</html>
	);
}
