import { Toaster } from 'react-hot-toast';
import Header from './components/header/Header';
import UploadModal from './components/modals/UploadModal';
import EditImageModal from './components/modals/EditImageModal';
import EditNameModal from './components/modals/EditNameModal';

import './globals.css';

import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Header />
				<UploadModal />
				<EditNameModal />
				<EditImageModal />
				<Toaster
					position='top-center'
					reverseOrder={false}
					toastOptions={{
						duration: 5000
					}}
				/>
				{children}
			</body>
		</html>
	);
}
